### ISSUE TITLE
[1.12] - Invalid shaped ore recipe: 111, 1M1, 111, 1, null, M, net.minecraft.item.ItemSeeds@214fba74,

### ISSUE THREAD

**Issue by Protheus** [Shadows-of-Fire/Growable-Cells#5]
Crash during loading of MC 1.12 with below error in crash log:

Pastebin: https://pastebin.com/1Fdux9pj

Forge: 2406
Growable Cells-1.12-2.3.1

What should happen: MC should not crash with above error and continue to load the game.

**Comment by Shadows-of-Fire** [comment]
Will continue with this on #6
