### ISSUE TITLE
Crashes on startup if you disable SpatialIO in Applied Config[1.12]

### ISSUE THREAD

**Issue by Fundryi** [Shadows-of-Fire/Growable-Cells#8]
https://gist.github.com/Fundryi/4925edfffe7da84ccbe2c46723548121

Maybe U can add some kind of check to disabled the specific recipes.
I tested this on a Server not Client, but it may be the same Issue.

**Comment by Shadows-of-Fire** [comment]
Should not happen as of 3.0.0
